# Generated by Django 6.0.2 on 2026-02-27 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_code',
            field=models.CharField(default=uuid.uuid4, help_text='Code used by employees to join this organization.', max_length=64, unique=True),
        ),
    ]
