# Generated by Django 6.0.2 on 2026-03-02 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_organization_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending User Action'), ('done', 'Authentication Complete'), ('invalid', 'Session Expired/Invalid')], default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, help_text='Stores the finalized NextAuth compatible payload (token, name, first_time, subscription)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
