# Generated by Django 6.0.2 on 2026-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_oauthsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('SOLO', 'Solo User')], default='EMPLOYEE', max_length=20),
        ),
    ]
