# Generated by Django 6.0.2 on 2026-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_seats',
            field=models.IntegerField(default=5, help_text='Maximum number of users allowed in this organization.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('SOLO', 'Solo User')], default='SOLO', max_length=20),
        ),
    ]
