# Generated by Django 6.0.2 on 2026-03-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_organization_max_seats_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invite_policy',
            field=models.CharField(choices=[('OPEN_LINK', 'Open Link (Auto-Join)'), ('APPROVAL_REQUIRED', 'Approval Required')], default='OPEN_LINK', max_length=25),
        ),
    ]
