# Generated by Django 6.0.2 on 2026-03-03 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_organization_invite_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftedSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted & Active'), ('REFUNDED', 'Expired & Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gifted Subscription',
                'verbose_name_plural': 'Gifted Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
