# Generated by Django 6.0.2 on 2026-03-03 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_giftedsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='online', max_length=50)),
                ('active_tracked_persons', models.IntegerField(default=0)),
                ('current_fps', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core_api.serviceaccount')),
            ],
            options={
                'verbose_name': 'CCTV Telemetry',
                'verbose_name_plural': 'CCTV Telemetry',
                'ordering': ['-created_at'],
            },
        ),
    ]
