# Generated by Django 6.0.3 on 2026-03-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_cctvtelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monitoring_seconds_used',
            field=models.PositiveIntegerField(default=0, help_text='Total seconds of posture monitoring used (free tier cap: 36000s / 10hrs).'),
        ),
    ]
