# Generated by Django 6.0.3 on 2026-03-06 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_add_monitoring_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvtelemetry',
            name='payload',
            field=models.JSONField(default=dict, help_text='Rich telemetry data including per-camera stats'),
        ),
        migrations.CreateModel(
            name='CCTVCamera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(help_text='Client-side unique ID for the camera (e.g. cam_01)', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('room_type', models.CharField(default='General', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='core_api.serviceaccount')),
            ],
            options={
                'verbose_name': 'CCTV Camera',
                'verbose_name_plural': 'CCTV Cameras',
                'unique_together': {('service_account', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='CCTVViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(max_length=100)),
                ('violator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('snapshot_url', models.URLField(blank=True, help_text='Link to the captured frame if uploaded', null=True)),
                ('payload', models.JSONField(default=dict, help_text='Additional metadata about the violation')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core_api.cctvcamera')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv_violations', to='core_api.organization')),
            ],
            options={
                'verbose_name': 'CCTV Violation',
                'verbose_name_plural': 'CCTV Violations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
