# Generated by Django 6.0.3 on 2026-03-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_cctvtelemetry_payload_cctvcamera_cctvviolation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftedsubscription',
            old_name='stripe_checkout_session_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='giftedsubscription',
            old_name='stripe_payment_intent_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='stripe_subscription_id',
            new_name='razorpay_subscription_id',
        ),
    ]
