# Generated by Django 6.0.3 on 2026-03-09 06:11

from django.db import migrations, models

def set_existing_users_verified(apps, schema_editor):
    CustomUser = apps.get_model('core_api', 'CustomUser')
    CustomUser.objects.update(is_email_verified=True)

class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_rename_stripe_checkout_session_id_giftedsubscription_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Tracks whether the user has verified their email address via token.'),
        ),
        migrations.RunPython(set_existing_users_verified, migrations.RunPython.noop),
    ]
