# Generated by helper on 2026-03-09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0013_processedwebhookevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=32, null=True, blank=True, help_text='Optional E.164 phone number for SMS verification.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text="Tracks whether the user's phone number has been verified."),
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to='core_api.customuser')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
