# Generated by helper on 2026-03-09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0014_add_phone_fields_and_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdWatch',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('provider', models.CharField(default='mock', max_length=100)),
                ('ad_id', models.CharField(max_length=255, null=True, blank=True)),
                ('validated', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(max_length=512, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_watches', to='core_api.customuser')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AdRewardGrant',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('grant_type', models.CharField(choices=[('CREDIT', 'Credit Seconds'), ('AI_ACCESS', 'AI Access Uses')], max_length=20)),
                ('amount_seconds', models.IntegerField(blank=True, null=True)),
                ('uses', models.IntegerField(default=0)),
                ('source', models.CharField(default='ads', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_rewards', to='core_api.customuser')),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
