# Generated by Django 5.1.15 on 2026-04-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_add_ad_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='monitoring_seconds_used',
            field=models.PositiveIntegerField(default=0, help_text='Total seconds of posture monitoring used (free tier cap: 604800s / 7 days).'),
        ),
    ]
